### ISSUE TITLE
Correction hauteur icone

### ISSUE THREAD

**Issue by Jeff-Le-Citoyen-Lambda** [datanfr/datan#127]
Il y a une petite erreur sur la dim d'un icone.
Sur cet page et les autres pages des députés :
https://datan.fr/deputes/ain-01/depute_damien-abad

![image](https://user-images.githubusercontent.com/80222864/112870692-c0564f80-90be-11eb-8811-560387b3c143.png)

**Comment by brissa-a** [comment]
Tu utilises quel navigateur ? J'arrive pas a reproduire le problème.

**Comment by Jeff-Le-Citoyen-Lambda** [comment]
je suis sur google Chrome

**Comment by remikel** [comment]
j'arrive pas non plus à reproduire :/
