### ISSUE TITLE
Ajout d'un indicateur - classe sociale

### ISSUE THREAD

**Issue by Jeff-Le-Citoyen-Lambda** [datanfr/datan#160]
Voir si nous pouvons ajouter la classe social des députés en fonction de leurs professions, il doit y avoir un jeux de donné la dessus.

On pourra connaitre les répartitions sociologiques des différents groupes :-). voir les croiser avec les votes etc cela est intéressant scientifiquement parlant je pense

**Comment by awenig** [comment]
Bonne idée ! Il faudra utiliser les indicateurs CSP déjà présents dans les bases.

**Comment by awenig** [comment]
Reste à faire : indicateurs par groupe

**Comment by Jeff-Le-Citoyen-Lambda** [comment]
Je ne sais pas ou tu prends les datas je crois qu'il y a une erreur sur Jean-Michel Mis, avant il était assistant parlementaire

**Comment by awenig** [comment]
Jean-Michel Mis a indiqué être un cadre du secteur privé : https://www2.assemblee-nationale.fr/deputes/fiche/OMC_PA719952 | C'est informations sont déclaratives, donc il faut croire le parlementaire dans sa déclaration...

**Comment by Jeff-Le-Citoyen-Lambda** [comment]
effectivement, ceci dit cela ne correspond pas à son dernier emplois qu'il a déclaré dans sa déclaration d'întérêt ... et cela peut fausser des stats, par exemple si on veut voir si les élus d'un parti sont issus de la société civile on peut considérer qu'un cadre du secteur privé vient bien de la société civil mais qu'un assistant parlementaire moins.

Je ne sais pas si on peut apporter une correction manuel, en notant au passage qu'il y a une erreur sur le site de l'AN (ce point là est vraiment à réfléchir, mais ca peut être gage de qualité de montrer à l'audience de DATAN que l'on vérifie les infos.)

Tris du projet Arcadie a bien noté cette différence. d'ailleur y'a peut être une réfléxion a avoir avec elle pour collaborer (à voir)
https://projetarcadie.com/content/jean-michel-mis

[mis-jean-michel-diam10991-depute-42.pdf](https://github.com/datanfr/datan/files/6482249/mis-jean-michel-diam10991-depute-42.pdf)

**Comment by awenig** [comment]
- [ ] Scrapping données haute autorité pour la transparence de la vie publique
