### ISSUE TITLE
Ajouter un bouton demande de vulgarisation.

### ISSUE THREAD

**Issue by Jeff-Le-Citoyen-Lambda** [datanfr/datan#316]
Ajouter un bouton demande de vulgarisation afin de savoir quelle loi les utilisateurs souhaitent que l’on traite.

Cela pourrait-être remonté dans le tableau de bord. 

Ou il y a les votes non publiés on pourrait avoir lois non vulgarisées "plébiscité" ou même permettre de voir quelles sont les pages de lois non vulgarisées qui ont le plus de visite.

**Comment by awenig** [comment]
C'est fait ;)
