### ISSUE TITLE
Les photos des députés dépassent du cadre

### ISSUE THREAD

**Issue by Nastaliss** [datanfr/datan#376]
Les photos dans la liste des députés ne sont pas centrées. Leurs têtes sont souvent coupée en haut.
![Before](https://user-images.githubusercontent.com/46960549/148644397-6e148b9a-0908-482d-b9b2-16174c016943.png)
En appliquant une marge de `0px` au lieu de `-10px` on arrive à un meilleur résultat.
![after](https://user-images.githubusercontent.com/46960549/148644434-e6f6abc4-c705-4af8-89b3-553be0bcf321.png)

**Comment by awenig** [comment]
Super merci ! Je vais faire ça ! Si tu veux contribuer au projet, n'hésite pas à nous faire un mail (info[at]datan.fr) pour discuter.
