### ISSUE TITLE
Le @ s'affiche mal

### ISSUE THREAD

**Issue by vico4445** [datanfr/datan#390]
Sur la page de l'élection 2022, l'adresse mail affiche [at] au lieu de @.
![image](https://user-images.githubusercontent.com/10618826/151706063-5b74eb44-5ea0-481a-a391-6e54f2bde4a6.png)

**Comment by awenig** [comment]
C'était pour éviter les spams, peut-être que cela ne sert à rien ? Merci beaucoup :) Si vous souhaitez contribuer au projet/code, n'hésitez pas à nous contacter !
