### ISSUE TITLE
Système de votation des lois vulgarisées

### ISSUE THREAD

**Issue by Jeff-Le-Citoyen-Lambda** [datanfr/datan#55]
Je pense que de donner la possibilité de voter sur les lois décryptés permettrait :
Je pense qu'une votation au jugement majoritaire serait bien :-)

- Au site d'être plus connu 
- Donnerai envie aux gens aux gens de s'informer sur les lois
- D'avoir des données sur l'adéquation d'une population 
- Nous pourrons créer du contenu pour les réseaux sociaux avec les résultats des votes.

Les limites sont les suivantes : les votants n'auront pas un avis d'expert sur les sujets, nous ne sommes pas certain de savoir si la personne a lu la vulgarisation avant de voter.

J'ai pu faire ca sur le site de Moi Citoyen Lambda avec le puggin poll démocraty. un site pas top avec une vulgarisation pas terrible terrible avait récolté pas mal de voix.

Exemple : 
https://moicitoyenlambda.org/?p=4658

Voici démocratie poll, le code est en libre de ce que j'ai pu comprendre 
https://fr.wordpress.org/plugins/democracy-poll/

**Comment by remikel** [comment]
C'est un peu ce qu'on va faire avec l'idée du questionnaire, la récompense pour l'utilisateur sera de savoir avec quel groupe (ou député) il partage le plus les idées.
