### ISSUE TITLE
Professions de foi 

### ISSUE THREAD

**Issue by awenig** [datanfr/datan#551]
https://programme-candidats.interieur.gouv.fr/index.html

**Comment by remikel** [comment]
Soit on crawl les pages et chaque lien pour récupérer les PDF.
Soit on les télécharge tous si on dispose de ces infos : 
ex : https://programme-candidats.interieur.gouv.fr/elections-legislatives-2022/data-pdf-propagandes/2-64-04-5.pdf
le 2 je ne sais pas à quoi il correspond mais il a l'air d'y être toujours
2ème nombre : département
3ème nombre : circonscription
4ème nombre : numéro du candidat

**Comment by awenig** [comment]
Oui, après les numéros des candidats le pbm est que ça doit se trouver, mais pas vraiment de possibilité de faire le lien entre le député et le numéro du candidat, sauf à faire un système basé sur la correspondance des noms+prénoms. Après j'ai vu des liens avec un exemple avec un `acc` ajouté dans l'URL, donc j'ai peur que leur propre système ne soit pas 100% clean : https://programme-candidats.interieur.gouv.fr/elections-legislatives-2022/candidats.html?circo=04&departement=56&tour=2

**Comment by awenig** [comment]
Sinon, on fait un robot qui récupère tous les députés actuels, élus en 2022, on va chercher la page sur le site (https://programme-candidats.interieur.gouv.fr/elections-legislatives-2022/candidats.html?circo=02&departement=22&tour=2) avec le numéro de `département`, la `circo`, et le `tour`, on cherche si il y a un match entre le nom du député et un nom de candidat, et si oui on télécharge sur nos serveurs le document ? Je pense que télécharger et mettre soit sur le serveur de datan soit sur github peut garder un historique, si le site du ministère les supprime toutes dans quelques années.

**Comment by brissa-a** [comment]
> Soit on crawl les pages et chaque lien pour récupérer les PDF. Soit on les télécharge tous si on dispose de ces infos : ex : https://programme-candidats.interieur.gouv.fr/elections-legislatives-2022/data-pdf-propagandes/2-64-04-5.pdf le 2 je ne sais pas à quoi il correspond mais il a l'air d'y être toujours 2ème nombre : département 3ème nombre : circonscription 4ème nombre : numéro du candidat
Le 2 c'est pour "tour 2"

**Comment by brissa-a** [comment]
Faut pas oublié les francais établis hors de france aussi
https://www.diplomatie.gouv.fr/fr/services-aux-francais/voter-a-l-etranger/elections-legislatives-2022/consulter-les-circulaires-des-candidats-et-voter-par-internet/

**Comment by awenig** [comment]
Liens AN: 

- https://www.assemblee-nationale.fr/dyn/decouvrir-l-assemblee/histoire/barodet2/recueil-des-professions-de-foi-de-la-15eme-legislature 
- https://www.assemblee-nationale.fr/dyn/decouvrir-l-assemblee/histoire/barodet2/recueil-des-professions-de-foi-de-la-16eme-legislature
