### ISSUE TITLE
Réagencer les villes les plus peuplés

### ISSUE THREAD

**Issue by remikel** [datanfr/datan#579]
On m'a fait remarquer qu'on a plus tendances à lire par colonne plutôt que par ligne, les villes les plus peuplés.
https://datan.fr/deputes/pyrenees-atlantiques-64

Soit retirer l'organisation par colonne et avoir les villes les unes à la suite des autres peut-être ( ça raccourcirait la page)
Soit mettre à la vertical plutôt qu'à l'horizontal

**Comment by awenig** [comment]
Je pense qu'on peut laisser par colonne comme ça, c'est surement plus lisible. Après c'est beaucoup pour le SEO cette fonctionnalité, moins utile pour les utilisateurs. Tu veux changer l'ordre (vertical plutôt qu'horizontal) ?

**Comment by remikel** [comment]
Ouais c'était juste une remontée, je trouve pas utile de changer ça au final...
