### ISSUE TITLE
Matomo ne me reconnait pas

### ISSUE THREAD

**Issue by remikel** [datanfr/datan#62]
Je suis au Mexique sans vpn la plupart du temps, je vais sur Datan.fr quasiment tous les jours mais Matomo n'arrive pas à me voir.
J'ai désactivé mon bloqueur sur datan.fr.

Quelqu'un saurait ?

**Comment by brissa-a** [comment]
matomo kesako ?

**Comment by remikel** [comment]
c'est le tracker qu'Awenig a installé, un peu comme google analytics mais plus soft qui ne se base que sur les IP, pas d'utilisation de cookies.

**Comment by awenig** [comment]
Plus GDPR friendly :) ==> https://www.armandphilippot.com/remplacer-google-analytics-par-piwik/#:~:text=Puisque%20Google%20Analytics%20n'est,la%20loi%20sur%20les%20cookies.
