### ISSUE TITLE
Faute d'orthographe 

### ISSUE THREAD

**Issue by nathanmutin** [datanfr/datan#662]
Il y a une faute sur les pages de votes dans la section concernant l'explication du vote.

A la ligne 20 du fichier application/views/votes/partials/explain.php

"Aucun député ne sait encore exprimé"
à remplacer par
"Aucun député ne s'est encore exprimé"

Merci pour le travail que vous faites c'est super !

**Comment by remikel** [comment]
Merci Nathan,
C'est corrigé côté code, ça sera bientôt déployé !

**Comment by awenig** [comment]
Merci beaucoup @nathanmutin !
