### ISSUE TITLE
Impossible de rafraîchir les données

### ISSUE THREAD

**Issue by LoicEm** [datanfr/datan#786]
J'ai suivi les étapes d'installation avec Docker, après `docker compose up` (et quelques minutes d'attente) j'ai une base de données principalement vide (les tables `votes_groupes`, `votes_info` ont par exemple 0 lignes).

Conformément aux instructions, je lance ensuite `npm run docker-download`.

## Ce que j'attendais

Le script tourne et les données se chargent, me permettant d'accéder aux votes de chaque député.e.

## Ce qu'il se produit

Le script me retourne une erreur

```
2024-06-20 : Launching the download script for legislature 16
Erreur : SQLSTATE[HY000] [1045] Access denied for user ''@'172.23.0.4' (using password: NO)
```

**Comment by arnaudsm** [comment]
Le .env par défaut ne fournit pas les variables de connexion à la DB (ou du moins avec le bon nom)

Il faut rajouter ceci dans ton `.env`: 
```
DATABASE_NAME=datan
DATABASE_USERNAME=datan
DATABASE_PASSWORD=datan
```

Je vais ouvrir une PR avec le changement
