### ISSUE TITLE
coquilles trouvé par Thomas P

### ISSUE THREAD

**Issue by remikel** [datanfr/datan#898]
https://datan.fr/deputes

Les dernières ont eu lieu en juin 2022.
7 juillet 2024.

Du fait de la dissolution de l'Assemblée nationale, décidée le 9 juin 2024 par le président Emmanuel Macron, des nouvelles élections législatives se dérouleront les 30 juin et 7 juillet 2024.
mis au présent de l’indicatif : 

Du fait de la dissolution de l'Assemblée nationale, décidée le 9 juin 2024 par le président Emmanuel Macron, des nouvelles élections législatives se sont  déroulées les 30 juin et 7 juillet 2024

Les 577 députés de la 16ème législature
17eme législature 

https://datan.fr/deputes/legislature-16
https://datan.fr/groupes

Historique
La législature actuelle est la 16ème législature. Elle a débuté en 2022, à la suite des élections législatives, et se terminera en 2027.
17eme législature
 Elle a débuté 7 juillet 2024
le lien pour les éléctions legislative est à mettre à jour.

**Comment by awenig** [comment]
Merci !! :)
