### ISSUE TITLE
Clean database

### ISSUE THREAD

**Issue by remikel** [datanfr/datan#9]
circos :
supprimer la colonne departement_nom_soundex - **mistake (unknown column)**

departement
supprimer les colonnes departement_nom_soundex et departement_nom_uppercase - 👍  **done**

Merger : = this has been done in the pull request : #10 
class_groups_cohesion
class_groups_majorite
class_groups_participation

Merger : = see pull request: #11 
departement
departements_regions
La 2ème n’est utilisé que sur un join de la première

Groupe_accord refacto : cf #31 
uid
voteNumero
organeRef1
organeRef2
GroupePosition1
GroupePosition2
Accord (optionnel)

Supprimer = done with #11 
regions_new_old et mettre le nouveau code dans la table insee

**Comment by awenig** [comment]
The following columns have been removed:

- departement.departement_nom_soundex 
- departement.departement_nom_uppercase

Run the following codes to update the SQL database:
`ALTER TABLE departement DROP departement_nom_uppercase`
`ALTER TABLE departement DROP departement_nom_soundex `

**Comment by remikel** [comment]
lancer le ton script du jour

**Comment by awenig** [comment]
**Dernière issue à voir : **

Groupe_accord refacto :
uid
voteNumero
organeRef1
organeRef2
GroupePosition1
GroupePosition2
Accord (optionnel)

Si je comprends bien, on passe d'une table "wide" à "long", autrement dit à la place d'avoir une ligne par groupe et par vote, avec tous les autres groupes en colonnes, on a une ligne par vote et par binôme de deux groupes, avec leur taux d'accord dans une seule colonne ?

**Comment by remikel** [comment]
c'est ça oui, t'en penses quoi ?

**Comment by awenig** [comment]
Oui si c'est utile ? Il faudra changer les scripts/queries qui dépendent de cette table, mais ouais cela fait + sens. Je peux m'en charger si tu veux, dis moi ?

**Comment by remikel** [comment]
Je pense que c'est mieux oui, et plus propre, les groupes sont variables, il faudrait pas avoir à changer la table à chaque fois qu'un nouveau groupe apparait. Le premier qui a le temps peut s'en occuper ^^.

Sinon la table deputes_contacts peut être supprimé et on remplit contacts_clean directement (on la renomme sans le clean comme ça c'est plus clean)

**Comment by remikel** [comment]
Je pense que c'est mieux oui, et plus propre, les groupes sont variables, il faudrait pas avoir à changer la table à chaque fois qu'un nouveau groupe apparait. Le premier qui a le temps peut s'en occuper ^^.

Sinon la table deputes_contacts peut être supprimé et on remplit contacts_clean directement (on la renomme sans le clean comme ça c'est plus clean)

**Comment by awenig** [comment]
Pour *groupe_accord* je peux regarder. Pour deputes_contacts je comprends pas, sorry :)

**Comment by remikel** [comment]
tu remplis la table deputes_contacts mais tu l'utilise jamais sauf pour remplir deputes_contacts_clean.
Du coup autant remplir directement deputes_contacts_clean et supprimer deputes_contacts.
(et renommer deputes_contacts_clean en deputes_contacts ^^)

**Comment by remikel** [comment]
deputes, deputes_all, deputes_last et deputes_contacts peuvent être fusionnées non ?

**Comment by awenig** [comment]
`deputes` c'est la base "brute", autrement dit ce qu'on récupère des open data. Elle n'entre pas directement en interaction avec le site. Ensuite on créé d'autres bases qui vont elles interagir avec le site. Ce sont les `deputes_all` et `deputes_last`. Ces deux je pense pas qu'elles puissent être fusionnées. En fait `deputes_all` prendre une ligne par député et par legisalture, alors que `deputes_last` récupère juste la dernière législature pour chaque député. Pour le moment le frontend utilise les deux, mais si tu as une autre solution ? Et pour `deputes_contacts` on peut bien entendu mettre les données de contact dans les `deputes_all` et `deputes_last`, si cela ne ralentit pas le query ? Ca enlèverait une query lors du chargement des pages députés.

**Comment by remikel** [comment]
donc deputes ne sert à rien, on pourrait remplir directement deputes_all et depute_last.
C'est quoi la différence entre "deputes_all where legislature=15" et depute_last ?
Mettre les contacts du depute dans la table des deputes_last ou all devrait être logiquement plus rapide.

**Comment by remikel** [comment]
Du coup on garde deputes_contact séparé.
Depute_last pourrait être une vue de depute_all, ça ne change rien dans le code mais ça évite de lancer un script pour remplir depute_last.

**Comment by remikel** [comment]
Finalement, ce que tu as fait est très bien, 0 changement là-dessus pour le moment.
Juste étudier la possibilité de se passer de la table intermédaire députés

**Comment by awenig** [comment]
Donc pas de vue ? Si oui, faut checker si c'est possible, je connais pas assez :)

**Comment by brissa-a** [comment]
Ya les vue "classique" qui sont sous la forme:
> CREATE VIEW `view_of_toto` AS SELECT * from toto;

Elles s'update toutes seules quand tu updates toto. Mais sont lentes a l'execution, et tu peux pas créer d'index dessus.

Et les "materialized" view qui sont sous la forme:
> CREATE TABLE `view_of_toto` AS SELECT * from toto;

il faut les update a la main, mais elles sont plus performantes a l'execution et tu peux créer des index dessus.

Ce qui est exactement ce que tu fais dans le code
>               CREATE TABLE deputes_last AS
>               SELECT da.*, dpt.libelle_1, dpt.libelle_2,
>               CASE WHEN (legislature = 15 AND dateFin IS NULL) THEN 1 ELSE 0 END AS active
>               FROM deputes_all da
>               JOIN (
>               SELECT mpId, MAX(legislature) AS legislatureLast
>               FROM deputes_all
>               GROUP BY mpId
>               ) x ON da.mpId = x.mpId AND da.legislature = x.legislatureLast
>               LEFT JOIN departement dpt ON dpt.departement_code = da.departementCode

D'ailleurs je te conseille de faire une view "classique" dés que tu as une requête un peu complexe a écrire. C'est plus simple a gérer

voila voila

**Comment by awenig** [comment]
D'accord merci @brissa-a . Donc si je comprends bien, les materialised views, c'est juste la création de tables sur des queries un peu complexes, et c'est déjà ce qui est pas mal fait sur le site pour la computation de pas mal de stats. Concernant les views classiques, elles doivent s'écrire où ? Si tu trouves un exemple sur le site ca pourrait m'aider à mieux comprendre. Merci d'avance :)
